### ISSUE TITLE
trigger que dan aparición a los enemigos de la mezquita

### ISSUE THREAD

**Issue by Th3Cod3** [Roloman2810/cueva-de-ladrones#2]
re ajustar los trigger que dan aparición a los enemigos de la mezquita por si sobre vuela hopper para no activarlos antes de entrar en área, si esto sucede ocasiona que las IA reaparezcan y disminuya los FPS del servidor por trabajar en un área que no estamos ni cerca.

**Comment by skulldirt** [comment]
Se disminuyo la altura de los trigger para que hopper no active innesesariamente  los show mas alejados.
