### ISSUE TITLE
Ocultar civiles

### ISSUE THREAD

**Issue by Th3Cod3** [Roloman2810/cueva-de-ladrones#3]
Los civiles aparecen desde el principio verificar los trigger que activan su SHOW/HIDE

**Comment by skulldirt** [comment]
Se verifico los Show/hide pero el problema se avoco al trigger que activa la aparicion. La altura de los mismo estaba copnfigurada en 0 porque no se presentaba ningun tipo de area donde la condición BLUFOR y PRESENT no se estaban llevando a cabo.
