### ISSUE TITLE
Explosiones en base

### ISSUE THREAD

**Issue by Th3Cod3** [Roloman2810/cueva-de-ladrones#4]
un vehículo y un helicóptero siguen explotando en base

**Comment by Th3Cod3** [comment]
Estuve viendo la posición de los helicópteros y están bien puesto sobre el piso. @skulldirt

**Comment by skulldirt** [comment]
NOTA: 
Suponemos que la aparición de los vehiculos se logran en primera instancia antes de que el modulo de ocultar objeto del terreno aplique su función. Por este motivo recurrimos a posicionar los vehiculos en lugares donde no haya colision con ningun tipo de objeto del mapa antes de que el modulo se active.
Problema Resuelto
