### ISSUE TITLE
Extra Tecnical

### ISSUE THREAD

**Issue by Th3Cod3** [Roloman2810/cueva-de-ladrones#6]
Analizar poner Thecnicals que se acerquen desde el NW por el desierto para que hopper, abata igual desde el NE para martillo.

**Comment by skulldirt** [comment]
Se coloco un BTR iraq y 2 Truck Iraq para que una vez activado el trigger de presencia en la mezquita se accionen su waypon hacia dicho lugar.

**Comment by skulldirt** [comment]
Se ajusto para que estos enemigos aparezcan en forma de oleadas desde el S por la carretra principal hasta la altura de la mezquita.
Doy por tarea concluida
